# Eureka Server? Port ??
server:
  port: 8761 # Eureka Server? ????? ???? ?? ??
  
eureka:
  client:
    register-with-eureka: false # ?? ??? ?????? ???? ??
    fetch-registry: false # ??? ??? ?? ?? (Gateway ??)
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka Server? ??